---
title: '🌈 Node.Js-205018-노드05일(write, read 복습)'
date: 2020-5-18 17:00:00
category: 'Node.Js'
draft: false
---

async await 할 때에는 try catch를 한다. 에러가 생겼는지도 모른다. 에러가 그대로 노출되게 해준다. 에러가 날 때에는 사용자에게 error status를 응답해준다. catch로 잡은 에러 결과를 throw로 전달해준다. 



# DB 모델링

